apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-green
  labels: 
    app: ubuntu-green
  annotations: {
    "opencontrail.org/network" : '{"domain": "default-domain", "project":"juniper","name":"vn-green"}'
  }
spec:
  containers:
    - name: ubuntu-green
      image: ubuntu-upstart

