apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-red
  labels: 
    app: ubuntu-red
  annotations: {
    "opencontrail.org/network" : '{"domain": "default-domain", "project":"juniper","name":"vn-red"}'
  }
spec:
  containers:
    - name: ubuntu-red
      image: ubuntu-upstart

