apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-blue
  labels: 
    app: ubuntu-blue
  annotations: {
    "opencontrail.org/network" : '{"domain": "default-domain", "project":"juniper2","name":"vn-blue"}'
  }
spec:
  containers:
    - name: ubuntu-blue
      image: ubuntu-upstart

