apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-a
  labels: 
    app: ubuntu-a
  annotations: {
    "opencontrail.org/network" : '{"domain": "default-domain", "project":"juniper","name":"vn-A"}'
  }
spec:
  containers:
    - name: ubuntu-a
      image: ubuntu-upstart

