apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-yellow
  labels: 
    app: ubuntu-yellow
  annotations: {
    "opencontrail.org/network" : '{"domain": "default-domain", "project":"juniper-iso2","name":"vn-yellow"}'
  }
spec:
  containers:
    - name: ubuntu-yellow
      image: ubuntu-upstart

