#!/bin/bash

for host in $(cat ~/contrail-ansible-deployer/config/all_hosts); do

(/mnt/config/sshpass -p contrail123 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -r \
/mnt/config \
/mnt/docker \
/mnt/www \
$host:/var/tmp) &

done
